collections:
  posts:
    output: true
    permalink: /:collection/:name
  tours:
    output: true
    permalink: /:collection/:name
  tours-inactive:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Ethnic Hilltribe Eco Trails
author:
  name: Ethnic Hilltribe Eco Trails
  email: EthnicHilltribeEcoTrails@gmail.com
  twitter:
social:
  name: Ethnic Hilltribe Eco Trails
  links:
    - ethnichilltribeecotrails.com

# Values for the jekyll-archives gem
jekyll-archives:
  enabled: 'all'
  layout: 'post-list'
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
